
b_evyth <- b_orig %>% 
  mutate(
    periodo = as.factor(paste0(anio, "_t", trimestre)),
    tipo_visitante_etiq = factor(tipo_visitante,
                                      levels = c(1,2),
                                      labels = c("Turista", "Excursionista")),
    transporte = factor(px09, 
                        levels = c(1:6, 8, 99),
                        labels = c("Automóvil o similar (propio)",
                                   "Omnibus",
                                   "Tren",
                                   "Avión",
                                   "Embarcación",
                                   "Taxi o remís",
                                   "Otro",
                                   "Ns./ Nr.")),
    motivo = factor(px10_1, 
                    levels = c(1:8, 99),
                    labels = c("Esparcimiento, ocio, recreacion",
                               "Visitas a familiares o amigos",
                               "Trabajo, negocios, motivos profesionales",
                               "Estudios y formación",
                               "Razones de salud",
                               "Motivos religiosos (peregrinaciones, etc.)",
                               "Compras",
                               "Otros",
                               "Ns./ Nr.")),
    tipo_alojamiento = factor(px08_agrup,
                              levels = c(1:7),
                              labels = c("Segunda vivienda del hogar",
                                         "Vivienda de familiares y amigos",
                                         "Vivienda alquilada por temporada",
                                         "Camping",
                                         "Hotel o similar hasta 3 estrellas",
                                         "Hotel similar 4 o 5 estrellas",
                                         "Resto")))

