
b_evyth <- b_orig %>% 
  mutate(
    periodo = as.factor(paste0(anio, "_t", trimestre)),
    tipo_visitante_etiq = factor(tipo_visitante,
                                      levels = c(1,2),
                                      labels = c("Turista", "Excursionista")),
    transporte = case_when(px09 %in% c(5,6,8) ~ 8,
                           TRUE ~ px09),
    transporte = factor(px09, 
                        levels = c(1:4, 8, 99),
                        labels = c("Automóvil o similar (propio)",
                                   "Omnibus",
                                   "Tren",
                                   "Avión",
                                   "Otro",
                                   "Ns./ Nr.")),
    motivo = case_when(px10_1 %in% c(4:8) ~ 8,
                       TRUE ~ px10_1),
    motivo = factor(px10_1, 
                    levels = c(1:3, 8, 99),
                    labels = c("Esparcimiento, ocio, recreacion",
                               "Visitas a familiares o amigos",
                               "Trabajo, negocios, motivos profesionales",
                               "Otros",
                               "Ns./ Nr.")),
    tipo_alojamiento = factor(px08_agrup,
                              levels = c(1:7),
                              labels = c("Segunda vivienda del hogar",
                                         "Vivienda de familiares y amigos",
                                         "Vivienda alquilada por temporada",
                                         "Camping",
                                         "Hotel o similar hasta 3 estrellas",
                                         "Hotel similar 4 o 5 estrellas",
                                         "Resto")))

