---
title: "Facilitando el acceso mediante reportes y tableros interactivos"
description: |
  Micrositio con recursos y datos actualizados de Turismo en Argentina. 
author:
  - name: Dirección Nacional de Mercados y Estadística
    url:
      https://www.yvera.tur.ar/estadistica/: {}
date: 09-09-2021
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

El micrositio [TABLEROS y REPORTES](https://tableros.yvera.tur.ar/) reune una serie de recursos que tienen como objetivo facilitar el acceso a los últimos datos disponibles de una multiplicidad de indicadores del turismo en Argentina.

## Reportes

1.  **Turismo Internacional**: presenta la última información de turismo receptivo, emisivo y balanza turística por todas las vías (aéreo, terrestre y fluvial / marítimo).

2.  **Ocupación Hotelera**: presenta los últimos datos disponibles de la *Encuesta de Ocupación Hotelera* (EOH)[^1].

3.  **Naturaleza**: presente información de visitas a Parques Nacionales del país [en base al *Registro Nacional de Autorizaciones, Recaudaciones e Infracciones* (RENARI)](http://datos.yvera.gob.ar/dataset/parques-nacionales) de la Administración de Parques Nacionales.

4.  **Turismo Interno**: Reporte de los últimos datos estimados por la *Encuesta de Viajes y Turismo de los Hogares* (EVyTH)[^2].

[^1]: [**Encuesta de Ocupación Hotelera (EOH)**](https://dnme-minturdep.github.io/DT1_medicion_turismo/encuestas-nacionales.html#eoh) es un relevamiento realizado en forma continua desde el 2004, bajo la coordinación del MINTURDEP y el [Instituto Nacional de Estadísticas y Censos (INDEC)](https://www.indec.gob.ar/indec/web/Nivel4-Tema-3-13-56).

[^2]: La [**Encuesta de Viajes y Turismo de los Hogares (EVyTH)**](https://dnme-minturdep.github.io/DT1_medicion_turismo/encuestas-nacionales.html#evyth) es un operativo realizado por el MINTURDEP, cuyo objetivo principal es proporcionar información sobre los viajes turísticos de los residentes de Argentina hacia dentro y fuera del país: cuándo viajan, a dónde van, qué medios de transporte utilizan, dónde se alojan, cuáles son los motivos por los que viajan, cómo organizan sus viajes, qué actividades turísticas realizan, cuánto gastan, etc.

## Tableros

### PUNA

El **Padrón Único Nacional de Alojamiento (PUNA)** reúne todos los establecimientos de alojamiento turístico de la Argentina, en el que se detallan las principales variables de cada uno, nutrido a partir de diferentes fuentes de información:

-   los organismos provinciales y municipales de turismo que a través de su área de fiscalización de servicios turísticos elabora el padrón de alojamiento de su provincia o localidad;

-   el INDEC a través de la *Encuesta de Ocupación Hotelera (EOH)*;

-   fuentes secundarias especializadas en turismo relevadas desde la DNMYE - MINTURDEP.

El [tablero PUNA](https://tableros.yvera.tur.ar/puna/) disponibiliza información histórica (2014 - 2019) que da cuenta de: cantidades de *(a) Establecimientos*; *(b) Unidades*; *(c) Habitaciones* y *(d) Plazas* registradas a distintos niveles de agregación (`Ruta`, `Región`, `Provincia`, `Departamento`o `Localidad`) y según *Clasificación* y *Tipo de establecimiento* (`hotelero`, `parahotelero`, `privados`y `otros colectivos`)

### TURISMO INTERNACIONAL

El [tablero](https://tableros.yvera.tur.ar/turismo_internacional/) presenta las estimaciones mensuales del turismo internacional -receptivo y emisivo- de la totalidad de los pasos fronterizos del país, desde el año 2016 hasta la actualidad. La información estadística que se presenta, basada en los registros migratorios provistos por la Dirección Nacional de Migraciones (DNM) y en la *Encuesta de Turismo Internacional (ETI)*[^3], se refiere al flujo de turistas no residentes que visitaron el país y de los turistas residentes que viajaron al exterior, por todos los medios de transporte (aéreo, fluvial/marítimo y terrestre).

[^3]: La [**Encuesta de Turismo Internacional (ETI)**](https://dnme-minturdep.github.io/DT1_medicion_turismo/encuestas-nacionales.html#eti) es otro operativo realizado en forma continua desde el año 2004, coordinado conjuntamente por el MINTURDEP y el [INDEC](https://www.indec.gob.ar/indec/web/Nivel4-Tema-3-13-55).

El mismo permite visualizar y descargar información detallada por año, mes, medio de transporte, paso fronterizo (con el detalle de la provincia y del país con el que limita el mismo), país de residencia para el turismo receptivo y destino principal para turismo emisivo. De esta manera, el tablero constituye una herramienta amigable para el manejo de los datos estadísticos de turismo internacional de nuestro país. Actualmente se encuentra disponible información actualizada hasta mayo 2021.

### 
