---
title: "Bienvenides"
description: |
 La Bitácora de Turismo es un espacio virtual de la Dirección Nacional de Mercados y Estadística (DNMyE) en el que nos proponemos compartir avances de investigaciones, datos y reportes relacionados con el desarrollo de la industria turística de Argentina. 
author:
  - name: Juan Pablo Ruiz Nicolini 
    affiliation: Dirección Nacional de Mercados y Estadística
date: 08-26-2021
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating blogs with Distill at:
# https://rstudio.github.io/distill/blog.html

```


_La Bitácora de Turismo_ es un nuevo paso de un plan de trabajo en el que se plantean una serie de objetivos alrededor de la producción, generación y acumulación de conocimiento útil para la toma de decisiones y el diseño de políticas públicas más y mejor informadas, y también al amplio abanico de actores del sector turístico: cámaras empresarias, la industria o la academia.

En este sentido, se trabajan las siguientes iniciativas:

* El procesamiento de un vasto acervo de información (de operativos estadísticos y registros administrativos, entre otros) y su paulatina apertura en el [Portal de Datos Abiertos de Turismo](http://datos.yvera.gob.ar/).

* La sistematización en la confección de [reportes y la generación de tableros](https://tableros.yvera.tur.ar/), con el objetivo de acercar la información de un modo más intuitivo a usuarias y usuarios que no cuenten con experiencia en procesamiento de bases de datos. 

* El lanzamiento de un proyecto de [_Armonización de las Estadísticas Provinciales de Turismo_](https://armonizacion.yvera.tur.ar/) que contempla una serie de actividades (diagnóstico, desarrollo de materiales, capacitaciones, foro de intercambio, generación de una herramienta de gestión de datos), con el objetivo de contribuir al fortalecimiento de los sistemas de estadística provinciales para generar información robusta y confiable de la actividad turística de nuestro país.

Les damos la bienvenida a _la Bitácora_, con la expectativa de que este espacio sea de utilidad para acercar el trabajo que se está llevando adelante desde el Ministerio de Turismo y Deportes de la Nación. 
